Repository lightspeeddevelopment/lsx, pull requests merged in 2020-03, with the labels that each got.

#318 Fix/events calendar upgrade
  assets/css/maps/gutenberg.css.map
  assets/css/the-events-calendar/maps/the-events-calendar-5.css.map
  assets/css/the-events-calendar/maps/the-events-calendar.css.map
  assets/css/the-events-calendar/the-events-calendar-5.css
  assets/css/the-events-calendar/the-events-calendar-5.scss
  assets/css/the-events-calendar/the-events-calendar.css
  assets/css/the-events-calendar/the-events-calendar.scss
  changelog.md
  gulpfile.js
  includes/the-events-calendar/the-events-calendar.php
Labels: enhancement

#338 Fix/336
  assets/css/maps/gutenberg.css.map
  assets/css/sensei/maps/sensei.css.map
  assets/css/sensei/sensei.css
  assets/css/sensei/sensei.scss
  assets/js/lsx.js
  assets/js/src/lsx.js
  changelog.md
  includes/sensei/class-lsx-sensei.php
Labels: bug, enhancement

#335 Fix - 334
  includes/extras.php
Labels: bug

#337 Fix/302
  changelog.md
  includes/classes/class-lsx-customize-layout-control.php
  includes/classes/class-lsx-schema-utils.php
  includes/config.php
  includes/hooks.php
  includes/sanitize.php
  includes/sensei/class-lsx-sensei.php
  includes/widgets.php
  page-templates/template-archives.php
  page-templates/template-front-page.php
  page-templates/template-full-width-no-margins.php
  page-templates/template-full-width.php
  page-templates/template-no-sidebar.php
  page-templates/template-sitemap.php
  page-templates/template-wc-thank-you.php
  partials/content-custom.php
  partials/content-none.php
  partials/content-page.php
  partials/content-post.php
  partials/content-related.php
  partials/content-widget-product.php
  partials/content-widget-review.php
  partials/content.php
  sidebar.php
  single.php
  tribe-events/day/single-event.php
  tribe-events/day/single-featured.php
  tribe-events/list/single-event.php
  tribe-events/list/single-featured.php
  tribe-events/pro/related-events.php
Labels: enhancement

#339 Add/wp 5.4 compatibility
  assets/css/gutenberg-rtl.css
  assets/css/gutenberg.css
  assets/css/maps/gutenberg.css.map
  assets/css/scss/layout/_banner.scss
  assets/css/scss/layout/_nav.scss
  assets/css/scss/layout/_search-form.scss
  assets/css/sensei/maps/sensei.css.map
  assets/css/sensei/sensei.css
  assets/css/sensei/sensei.scss
  assets/css/the-events-calendar/maps/the-events-calendar-5.css.map
  assets/css/the-events-calendar/the-events-calendar-5.css
  assets/css/the-events-calendar/the-events-calendar-5.scss
  changelog.md
Labels: bug, enhancement

#342 * Fixed - Fixing the default banner for the events archives
  changelog.md
  includes/the-events-calendar/the-events-calendar.php
Labels: bug

#343 #267 - Fixing the custom banner title for the events archives
  changelog.md
  includes/the-events-calendar/the-events-calendar.php
Labels: bug

#344 Fix/sensei small bug fixes
  assets/css/gutenberg-rtl.css
  assets/css/gutenberg.css
  assets/css/maps/gutenberg.css.map
  assets/css/scss/global/mixins/_banner.scss
  assets/css/sensei/maps/sensei.css.map
  assets/css/sensei/sensei.css
  assets/css/sensei/sensei.scss
  includes/sensei/class-lsx-sensei-course.php
  includes/sensei/class-lsx-sensei.php
  partials/content.php
Labels: enhancement, performance

#341 Change style to make the WC filter blocks look like LSX search on mobile.
  assets/css/woocommerce/maps/woocommerce.css.map
  assets/css/woocommerce/woocommerce-extensions/_woocommerce-blocks.scss
  assets/css/woocommerce/woocommerce.css
  assets/js/lsx.js
  assets/js/src/lsx.js
  changelog.md
Labels: enhancement
